### PR TITLE
Add block stats aggregates

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Collect block stats aggregates.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Y u no merge?

**Comment by imsodin** [comment]
I guess the message above had an implicit @calmh, but as it's not there explicitly: This looks reasonable to me, but I don't know SQL, so no explicit lgtm from me.

**Comment by calmh** [comment]
Yeah I don't understand the SQL either. Does it work? If so, push it and deploy it I guess.

**Comment by AudriusButkevicius** [comment]
It does, I ran the first round on the live db (as we seem not to handle running the first round automatically).

**Comment by AudriusButkevicius** [comment]
I thought people will ask what does `LEAD(Uptime) OVER (PARTITION BY UniqueID ORDER BY Received) - Uptime AS UptimeDiff` do, but I guess nobody cares.

**Comment by imsodin** [comment]
I could also have asked why you create `BlockStatsDayIndex` and then it doesn't come up anywhere else in the diff, as well of lots of other stuff, but I assumed the best answer to all of these questions would be "learn SQL", which wouldn't improve the review :P

**Comment by calmh** [comment]
I was actually silently impressed by the `LEAD(Uptime) OVER (PARTITION BY UniqueID ORDER BY Received) - Uptime AS UptimeDiff` and realized that since I have no idea what that means reviewing this was out of my league.

**Comment by canton7** [comment]
Maybe this is an indication that some comments would have been helpful for the sanity of future maintainers?

**Comment by AudriusButkevicius** [comment]
To be honest, I was thinking of sprinkling a bit of that LEAD magic elsewhere, because if we have a device that reports itself multiple times a day, that artificially increases the count.

**Comment by AudriusButkevicius** [comment]
And yeah, I should add a comment.

**Comment by calmh** [comment]
That can't happen because there's a unique index on (device ID, day)

**Comment by AudriusButkevicius** [comment]
Just realized that block stats are somewhat moot as it stands now. We report ever growing sums, yet we don't have any kind of variable to indicate different runs between restarts. I tried doing it based on uptime for the next row for a given device becoming negative (LEAD), yet this means that reports that span over multiple days will only land on the day they the device gets restarted, which is not ideal

Even if the device doesn't get restarted, restarting the folder (due to some setting changing whatever), resets the block stats, meaning that you can have a sudden drop in stats in the ever growing sum.

I should change that to report differences between this report and last report, yet at the same time do not reset the diff if we are just looking at a report preview.

**Pull request merged**
